# Numpy

In [5]:
import numpy as np

### 데이터 생성하여 ndarray 형태로 변환

#### ※ ndarray : 넘파이의 데이터 타입 (다차원 배열 가능)


In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

### 변수 a의 타입 알아보기

In [7]:
type(a)

numpy.ndarray

### a의 행과 열 수 알아보기

In [4]:
a.shape

(3,)

In [8]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 3)

In [11]:
c=np.array([[1,2,3]])
c

array([[1, 2, 3]])

In [12]:
type(c)

numpy.ndarray

In [13]:
c.shape

(1, 3)

### 각 array가 몇 차원인지 확인하기

In [14]:
a.ndim

1

In [15]:
b.ndim

2

#### ndarray 안에 들어가 있는 데이터값은 정수(int), 실수(float), 문자열(str), 불(bool) 모두 가능
#### 하나의 ndarray안에는 같은 데이터타입을 가지는 데이터값만 들어올 수 있음
#### 만약 다른 데이터 타입을 가지는 데이터값이 있다면, 크기가 가장 큰 데이터 타입으로 형변환을 하여 일괄 적용함

### 데이터 값의 데이터타입 알아보기

In [16]:
a.dtype

dtype('int32')

### 데이터값을 다른 데이터타입으로 변환하기

In [17]:
a.astype('float64')

array([1., 2., 3.])

### ndarray 생성하기 - arange
#### 범위를 설정하면 범위안에서 값을 생성
#### 파이썬의 range와 유사

arange(시작하는 값, 끝나는 값 다음 값, 변하는 값)

변하는 값이 +1일 경우 생략가능

시작하는 값이 0일 경우 생략가능

In [18]:
d=np.arange(4, 10, 1)
d

array([4, 5, 6, 7, 8, 9])

In [19]:
d=np.arange(4, 10, 2)
d

array([4, 6, 8])

In [20]:
d=np.arange(4, 10)
d

array([4, 5, 6, 7, 8, 9])

In [21]:
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ndarray 생성하기 -  linspace

#### linspace(시작, 끝, 개수)

#### 디폴트로 모든 데이터값의 데이터타입은 float64

In [22]:
g=np.linspace(1,10,10)
g

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
g=np.linspace(1,10,20)
g

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### ndarray 생성하기 - zeros
#### 모든 값을 0으로 채운 ndarray 생성

In [25]:
e=np.zeros((3,2))
e

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
e=np.zeros((3,2), dtype=('int32'))
e

array([[0, 0],
       [0, 0],
       [0, 0]])

### ndarray 생성하기 - ones
#### 모든 값을 1으로 채운 ndarray 생성

In [27]:
f=np.ones((3,2), dtype=('int32'))
f

array([[1, 1],
       [1, 1],
       [1, 1]])

### ndarray의 차원 변경하기

In [28]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1=a.reshape(2,5)
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
a2=a.reshape(5,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

reshape에서 지정한 사이즈로 변경이 불가능하면 오류가 발생한다

In [31]:
a3=a.reshape(3,5)
a3

ValueError: cannot reshape array of size 10 into shape (3,5)

#### 인자를 -1로 적용하는 경우는 다른 인자에 맞춰서 적용해줌

In [32]:
a4=a.reshape(-1,5)
a4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
a5=a.reshape(2,-1)
a5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 인덱싱

#### 특정 데이터를 추출, 수정

In [34]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[3]

3

In [36]:
a[-1]

9

In [37]:
a[4]=10
a

array([ 0,  1,  2,  3, 10,  5,  6,  7,  8,  9])

#### 2차원에서 특정데이터 추출, 수정

In [38]:
b=np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
b=b.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b[1][2]

6

In [41]:
b[1][2]=10
b

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

#### 슬라이싱

[시작위치, 끝나는위치+1]

In [42]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a[2:5]

array([2, 3, 4])

In [44]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [45]:
a[:6]

array([0, 1, 2, 3, 4, 5])

2차원에서 슬라이싱

In [46]:
b

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

In [47]:
b=np.arange(1,10)
b=b.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
b[0:2, 1:3]

array([[2, 3],
       [5, 6]])

### 불리언 인덱싱 (Boolean indexing)

In [48]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 조건에 해당하는 데이터값만 추출

In [49]:
a1=a[a>4]
a1

array([5, 6, 7, 8, 9])

#### 조건에 따라 True 또는 False 값을 반환

In [50]:
a2=a>4
a2

array([False, False, False, False,  True,  True,  True,  True,  True])

In [51]:
a3=a[a>4]
a3

array([5, 6, 7, 8, 9])

### 행렬의 정렬
#### no.sort() : 원 행렬은 유지한 채 정렬된 행렬을 반환 

In [52]:
a=np.array([6,3,1,9])
a

array([6, 3, 1, 9])

In [53]:
b=np.sort(a)
b

array([1, 3, 6, 9])

In [54]:
a

array([6, 3, 1, 9])

#### ndarray.sort() : 원 행렬 자체를 정렬

In [55]:
a.sort()
a

array([1, 3, 6, 9])

#### 행 별로, 열 별로 정렬

axis 0 : row(행)

axis 1 : column(열)

In [56]:
b=np.array([[5,4,1],[3,2,6]])
b

array([[5, 4, 1],
       [3, 2, 6]])

In [57]:
np.sort(b, axis=0)

array([[3, 2, 1],
       [5, 4, 6]])

In [58]:
np.sort(b, axis=1)

array([[1, 4, 5],
       [2, 3, 6]])

#### 정렬된 행렬의 인덱스 알아보기

행렬을 정렬하면 해당 값의 인덱스는 어떻게 될까?

In [59]:
a=np.array([6,3,1,9])
a1=np.argsort(a)
a1

array([2, 1, 0, 3])

### random 함수

#### random.rand : 괄호안의 숫자의 개수에 따라 적합한 numpy배열로  0 이상 1 미만의 임의의 값을 추출

In [62]:
np.random.rand()

0.31548836145881565

In [66]:
np.random.rand(2,3)

array([[0.05499141, 0.6282558 , 0.75903787],
       [0.62838802, 0.81089338, 0.03817226]])

#### random.randint : 지정한 값 사이의 정수를 랜덤으로 호출

In [70]:
np.random.randint(1,10)

1

In [77]:
np.random.randint(1,10,(5,5))

array([[3, 9, 7, 8, 7],
       [1, 4, 8, 4, 8],
       [8, 6, 2, 8, 7],
       [5, 4, 5, 1, 8],
       [5, 9, 4, 8, 3]])

### 행렬 연산

In [78]:
a=np.array([1,2,3,4,5])
a+10

array([11, 12, 13, 14, 15])

In [80]:
a-10

array([-9, -8, -7, -6, -5])

In [81]:
a*2

array([ 2,  4,  6,  8, 10])

In [82]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [83]:
b=np.array([6,7,8,9,10])

In [84]:
a+b

array([ 7,  9, 11, 13, 15])

In [85]:
a*b

array([ 6, 14, 24, 36, 50])

### 선형대수 연산
#### 행렬 내적

In [0]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])

In [72]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

#### 전치 행렬

In [73]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])